### PR TITLE
scipy 1.9.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
`RuntimeError: The installed `pythran` is too old, >= 0.11.0 is needed, 0.10.0 detected`.
We have to update pythran to >=0.11.0 https://github.com/serge-sans-paille/pythran/tree/0.11.0

**Comment by cbouss** [comment]
Updated pythran to 0.11.0

**Comment by cbouss** [comment]
Now missing boost:
```
         INFO     File "scipy/_lib/setup.py", line 32, in configuration         
         INFO       check_boost_submodule()                                     
         INFO     File "scipy/_lib/setup.py", line 8, in check_boost_submodule  
         INFO       raise RuntimeError("Missing the `boost` submodule! Run `git 
                submodule "                                                     
         INFO   RuntimeError: Missing the `boost` submodule! Run `git submodule 
                update --init` to fix this.         
```

**Comment by cbouss** [comment]
The build now requires meson and meson-python instead of setuptools

**Comment by cbouss** [comment]
Tested on linux-64. py38, py39 return no errors. py310 has these failures:
`=========================== short test summary info ============================
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex8-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex8-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex8-csc_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex16-array]
FAILED sparse/linalg/tests/test_propack.py::test_examples[False-complex8]
FAILED sparse/linalg/tests/test_propack.py::test_examples[True-complex8]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex16-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex8-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex16-csc_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex8-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex16-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex16-csc_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex16-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_examples[True-complex16]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex8-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex16-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex8-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex8-csc_matrix]
= 18 failed, 49456 passed, 2829 skipped, 253 xfailed, 9 xpassed, 274 warnings in 637.38s (0:10:37) =`

With gdb I get: 
`sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex8-array] <- ../../envs/test_env/lib/python3.10/site-packages/scipy/sparse/linalg/tests/test_propack.py
Program received signal SIGSEGV, Segmentation fault.
0x00007fe3c5f9426f in mkl_blas.cdotc () from /opt/conda/envs/test_env/lib/python3.10/site-packages/mkl/../../../libmkl_intel_lp64.so.1
(gdb) bt
#0  0x00007fe3c5f9426f in mkl_blas.cdotc () from /opt/conda/envs/test_env/lib/python3.10/site-packages/mkl/../../../libmkl_intel_lp64.so.1
#1  0x00007fe3b4dced1b in clanbpro (m=10, n=20, k0=0, k=11, aprod=aprod@entry=0x7fe3b4db6790 <cb_caprod_in___user__routines>, u=..., ldu=10, v=..., ldv=20, b=..., ldb=11, rnorm=2.87866354,
    soption=..., ioption=..., swork=..., cwork=..., iwork=..., cparm=..., iparm=..., ierr=0) at /usr/local/src/conda/scipy-1.9.0/scipy/sparse/linalg/_propack/PROPACK/complex8/clanbpro.F:472
#2  0x00007fe3b4dbbb44 in clansvd_irl (which=..., jobu=..., jobv=..., m=10, n=20, dim=11, p=8, neig=3, maxiter=1000, aprod=0x7fe3b4db6790 <cb_caprod_in___user__routines>, u=..., ldu=10,
    sigma=..., bnd=..., v=..., ldv=20, tolin=9.99999975e-05, work=..., lwork=1149, cwork=..., lcwrk=350, iwork=..., liwork=88, soption=..., ioption=..., info=0, cparm=..., iparm=...,
    _which=1, _jobu=1, _jobv=1) at /usr/local/src/conda/scipy-1.9.0/scipy/sparse/linalg/_propack/PROPACK/complex8/clansvd_irl.F:224
#3  0x00007fe3b4db6601 in f2py_rout__cpropack_clansvd_irl (capi_self=<optimized out>, capi_args=<optimized out>, capi_keywds=<optimized out>, f2py_func=0x7fe3b4dbb5f0 <clansvd_irl>)
    at build/src.linux-x86_64-3.10/scipy/sparse/linalg/_propack/_cpropackmodule.c:1592
#4  0x00005574c477fffc in _PyObject_Call (tstate=0x5574c4dc6610, callable=<fortran at remote 0x7fe3b4ee3ab0>, args=
    ('L', 'y', 'y', 10, 20, 8, 3, 1000, <_AProd(A=<MatrixLinearOperator(dtype=<numpy.dtype[complex64] at remote 0x7fe3cf69bd00>, shape=(10, 20), A=<numpy.ndarray at remote 0x7fe3b0795f50>, _MatrixLinearOperator__adj=<_AdjointMatrixOperator(A=<numpy.ndarray at remote 0x7fe3b0796f70>, _AdjointMatrixOperator__adjoint=<...>, args=(<...>,), shape=(20, 10)) at remote 0x7fe3b07a90f0>, args=(<numpy.ndarray at remote 0x7fe3b0795f50>,)) at remote 0x7fe3b07a8ee0>) at remote 0x7fe3b07a8ac0>, <numpy.ndarray at remote 0x7fe3b0796910>, <numpy.ndarray at remote 0x7fe3b0795c50>, <float at remote 0x7fe3b4ee8850>, <numpy.ndarray at remote 0x7fe3b0795ad0>, <numpy.ndarray at remote 0x7fe3b0796850>, <numpy.ndarray at remote 0x7fe3b0795e90>, <numpy.ndarray at remote 0x7fe3b07963d0>, <numpy.ndarray at remote 0x7fe3b0796730>, <numpy.ndarray at remote 0x7fe3b0796430>, <numpy.ndarray at remote 0x7fe3b0796370>), kwargs=<optimized out>)
    at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:305
#5  0x00005574c481b774 in PyObject_Call (kwargs=0x0,
    args=('L', 'y', 'y', 10, 20, 8, 3, 1000, <_AProd(A=<MatrixLinearOperator(dtype=<numpy.dtype[complex64] at remote 0x7fe3cf69bd00>, shape=(10, 20), A=<numpy.ndarray at remote 0x7fe3b0795f50>, _MatrixLinearOperator__adj=<_AdjointMatrixOperator(A=<numpy.ndarray at remote 0x7fe3b0796f70>, _AdjointMatrixOperator__adjoint=<...>, args=(<...>,), shape=(20, 10)) at remote 0x7fe3b07a90f0>, args=(<numpy.ndarray at remote 0x7fe3b0795f50>,)) at remote 0x7fe3b07a8ee0>) at remote 0x7fe3b07a8ac0>, <numpy.ndarray at remote 0x7fe3b0796910>, <numpy.ndarray at remote 0x7fe3b0795c50>, <float at remote 0x7fe3b4ee8850>, <numpy.ndarray at remote 0x7fe3b0795ad0>, <numpy.ndarray at remote 0x7fe3b0796850>, <numpy.ndarray at remote 0x7fe3b0795e90>, <numpy.ndarray at remote 0x7fe3b07963d0>, <numpy.ndarray at remote 0x7fe3b0796730>, <numpy.ndarray at remote 0x7fe3b0796430>, <numpy.ndarray at remote 0x7fe3b0796370>), callable=<fortran at remote 0x7fe3b4ee3ab0>)
    at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:317
#6  do_call_core (kwdict=0x0,
    callargs=('L', 'y', 'y', 10, 20, 8, 3, 1000, <_AProd(A=<MatrixLinearOperator(dtype=<numpy.dtype[complex64] at remote 0x7fe3cf69bd00>, shape=(10, 20), A=<numpy.ndarray at remote 0x7fe3b0795f50>, _MatrixLinearOperator__adj=<_AdjointMatrixOperator(A=<numpy.ndarray at remote 0x7fe3b0796f70>, _AdjointMatrixOperator__adjoint=<...>, args=(<...>,), shape=(20, 10)) at remote 0x7fe3b07a90f0>, args=(<numpy.ndarray at remote 0x7fe3b0795f50>,)) at remote 0x7fe3b07a8ee0>) at remote 0x7fe3b07a8ac0>, <numpy.ndarray at remote 0x7fe3b0796910>, <numpy.ndarray at remote 0x7fe3b0795c50>, <float at remote 0x7fe3b4ee8850>, <numpy.ndarray at remote 0x7fe3b0795ad0>, <numpy.ndarray at remote 0x7fe3b0796850>, <numpy.ndarray at remote 0x7fe3b0795e90>, <numpy.ndarray at remote 0x7fe3b07963d0>, <numpy.ndarray at remote 0x7fe3b0796730>, <numpy.ndarray at remote 0x7fe3b0796430>, <numpy.ndarray at remote 0x7fe3b0796370>), func=<fortran at remote 0x7fe3b4ee3ab0>,
    trace_info=0x7fffbed37590, tstate=<optimized out>) at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5919
#7  _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4277
#8  0x00005574c47c7742 in _PyEval_EvalFrame () at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
#9  _PyEval_Vector (tstate=<optimized out>, con=0x7fe3b4f00170, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>)
    at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
#10 0x00005574c473d0b5 in _PyObject_VectorcallTstate (kwnames=('k', 'which', 'irl_mode', 'tol'), nargsf=<optimized out>, args=<optimized out>, callable=<function at remote 0x7fe3b4f00160>,
    tstate=<optimized out>) at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
#11 PyObject_Vectorcall () at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:123
#12 call_function (kwnames=('k', 'which', 'irl_mode', 'tol'), oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7fffbed377c0, tstate=<optimized out>)
    at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5867
#13 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4231
#14 0x00005574c47c7742 in _PyEval_EvalFrame () at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46`

This seems to be related to https://github.com/scipy/scipy/issues/15108

**Comment by cbouss** [comment]
superseded by https://github.com/AnacondaRecipes/scipy-feedstock/pull/19 (scipy 1.9.1)

**Pull request closed without merging**
