### PR TITLE
[PKG-1332] Minor SciPy update to v1.10.1

### PR DESCRIPTION
**Pull request by schuylermartin45**
- Updates SciPy to v1.10.1
- This fixes a reported bug for a customer

### CODE REVIEW

**Comment by schuylermartin45** [comment]
So far, some of these linting rules are blocked by (as in needs) this work: https://github.com/AnacondaRecipes/meson-python-feedstock/pull/4

**Comment by schuylermartin45** [comment]
For the sake of visibility, I would suggest reading [the latest commit message](https://github.com/AnacondaRecipes/scipy-feedstock/commit/7163d668805098634142586ed8cf0359c3f04869) on why I've reverted back to my original commit.

tl;dr `mesonpy` continues to give us grief and given the customer urgency in this request, we have abandoned trying to appease the linter for the time being. More work will likely need to be done at a future date.

**Comment by schuylermartin45** [comment]
Note: `host_section_needs_exact_pinnings` still fails on the linter. According to Marco, this is safe to ignore as the linter isn't updated on Prefect.

Running the latest version of the linter locally does not generate this message.

**Review by cbouss — APPROVED** [review]
LGTM!

**Pull request merged**
