### PR TITLE
Build 1.7.3 b2 (fix numpy pinnings in host)

### PR DESCRIPTION
**Pull request by pseudoyim**
Rebuild with correct `numpy` pinning in the **host** requirements to address this error:
```
>>> import scipy.special
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/siu/dev/numba.py39np120.conda/lib/python3.9/site-packages/scipy/special/__init__.py", line 643, in <module>
    from . import _ufuncs
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
>>>
```

Concourse builds (for `linux-ppc64le` and `win-64`, which failed on Prefect): https://concourse.build.corp.continuum.io/teams/main/pipelines/pyim_scipy_1.7.3_b2

### CODE REVIEW

**Review by cbouss — APPROVED** [review]
LGTM, assuming the resulting package works for different versions of numpy.

**Comment by pseudoyim** [comment]
> assuming the resulting package works for different versions of numpy.

Thanks @cbouss. I tested the latest osx-arm64 py39 build (build number `_2`) in c3i_test2 and it seems to resolve the problem that Siu originally reported above. Imported successfully with np119, np121, and np122 installed in the env.

Also Siu reported that their tests ran successfully when building against the new build (build number `_2`) in c3i_test2.

**Review by varlackc — COMMENTED** [review]
There seem to be a broken link on the current  `doc_url`
https://github.com/AnacondaRecipes/scipy-feedstock/blob/cc74fac50d65b723878788d7bfd22a916aab4eac/recipe/meta.yaml#L188

The following `URL` seems to be the updated documentation:
https://docs.scipy.org/doc/scipy/

**Review by varlackc — APPROVED** [review]
LGTM

**Comment by katietz** [comment]
thanks!

**Pull request merged**
